### ISSUE TITLE
Failed to exec 'vagrant up' (rbenv, ruby 2.7.6, bundler 2.3.19, virtualbox)

### ISSUE THREAD

**Issue by cmhe** [voxpupuli/beaker#1752]
When trying to run tests with beaker, I am getting a `Failed to exec 'vagrant up'` error.

I am using `rbenv`, `ruby 2.7.6p219`, `bundler 2.3.19`. I found this issue on my host system, but I could also reproduce it inside a virtualbox machine (with nested virtualization enabled).

## Steps to reproduce it:

In order to easily reproduce this, I setup a virtualbox system using vagrant:

Vagrantfile to create virtual machine for testing:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder ".", "/project"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 6
    vb.memory = 8192
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vagrant build-essential fasttrack-archive-keyring zlib1g-dev
    mkdir -p /etc/apt/sources.list.d
    echo "deb http://deb.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list
    echo "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib" > /etc/apt/sources.list.d/fastrack.list
    echo "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib" >> /etc/apt/sources.list.d/fastrack.list
    apt-get update
    apt-get install -y virtualbox virtualbox-dkms virtualbox-guest-utils
    sudo -u vagrant -H -s <<-EOF
      curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      echo 'export PATH="\\\$HOME/.rbenv/bin:\\\$PATH"' >> ~/.bashrc
      echo 'eval "\\\$(rbenv init -)"' >> ~/.bashrc
EOF
SHELL
end
```

This vagrant file simply sets up a debian 11 virtual machine, with the latest rbenv, virtualbox and vagrant installed.

Create and enter the virtual machine with `vagrant up` and `vagrant ssh`. And then make some preparations:

```
$ rbenv install 2.7.6
$ cd /project
$ rbenv local 2.7.6
$ gem install bundler:2.3.19
```

Gemfile:
```
source "https://rubygems.org"

gem "rake"
gem "beaker", "~> 4.37"
gem "beaker-vagrant", "~> 0.7.1"
```

Rakefile:
```
require 'beaker/tasks/quick_start'
```

Then I just followed the quick start tutorial:

```
$ bundle config set --local path vendor/bundle && bundle install
$ bundle exec rake beaker_quickstart:gen_hosts[vagrant]
$ bundle exec rake beaker_quickstart:gen_pre_suite
$ bundle exec rake beaker_quickstart:gen_smoke_test
$ bundle exec rake beaker_quickstart:run_test[vagrant]
```

At this point I would have expected the test to setup the nested virtualbox machine and run the quickstart tests there, howerever I got the following error:

```
$ bundle exec rake beaker_quickstart:run_test[vagrant]
About to run - beaker-hostgenerator ubuntu1404-64default.mdcal-ubuntu1404-64af, --hypervisor=vagrant, --global-config={box_url=https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm,box=puppetlabs/ubuntu-14.04-64-nocm}
Not overwriting Host Config File: acceptance/config/default_vagrant_hosts.yaml - it already exists.
Not overwriting Pre Suite File: acceptance/setup/default_pre_suite.rb - it already exists.
Not overwriting Smoke Test File: acceptance/tests/default_smoke_test.rb - it already exists.
About to run - beaker --hosts acceptance/config/default_vagrant_hosts.yaml --pre-suite acceptance/setup/default_pre_suite.rb --tests acceptance/tests/default_smoke_test.rb
Beaker::Hypervisor, found some vagrant boxes to create
Failed: errored in CLI.initialize_network_manager
#<RuntimeError: Failed to exec 'vagrant up'. Error was /usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException)
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:300:in `activate_bin_path'
        from /usr/bin/vagrant:23:in `<main>'
>
/project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/bin/beaker:9
Failed: errored in CLI.provision
#<RuntimeError: Failed to exec 'vagrant up'. Error was /usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException)
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:300:in `activate_bin_path'
        from /usr/bin/vagrant:23:in `<main>'
>
/project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/bin/beaker:9
Traceback (most recent call last):
        15: from /project/vendor/bundle/ruby/2.7.0/bin/beaker:23:in `<main>'
        14: from /project/vendor/bundle/ruby/2.7.0/bin/beaker:23:in `load'
        13: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/bin/beaker:9:in `<top (required)>'
        12: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/cli.rb:71:in `provision'
        11: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/cli.rb:85:in `initialize_network_manager'
        10: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:71:in `provision'
         9: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:71:in `each_key'
         8: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:72:in `block in provision'
         7: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/hypervisor.rb:37:in `create'
         6: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:252:in `provision'
         5: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:265:in `vagrant_cmd'
         4: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:265:in `chdir'
         3: from /project/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:268:in `block in vagrant_cmd'
         2: from /home/vagrant/.rbenv/versions/2.7.6/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from /home/vagrant/.rbenv/versions/2.7.6/lib/ruby/2.7.0/open3.rb:219:in `popen_run'
/project/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:274:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant up'. Error was /usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException) (RuntimeError)
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:300:in `activate_bin_path'
        from /usr/bin/vagrant:23:in `<main>'
```

Beaker did create the `Vagrantfile` and creating this manually seems possible (apart from the Vagrantfile being wrong apparently):

```
$ cd .vagrant/beaker_vagrant_files/beaker_default_vagrant_hosts.yaml/
$ vagrant up
Bringing machine 'ubuntu1404-64-1' up with 'virtualbox' provider...
Bringing machine 'ubuntu1404-64-2' up with 'virtualbox' provider...
==> ubuntu1404-64-1: Box 'generic/ubuntu1404' could not be found. Attempting to find and install...
    ubuntu1404-64-1: Box Provider: virtualbox
    ubuntu1404-64-1: Box Version: >= 0
==> ubuntu1404-64-1: Loading metadata for box 'https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm'
    ubuntu1404-64-1: URL: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: generic/ubuntu1404
Actual name: puppetlabs/ubuntu-14.04-64-nocm
```

After replacing both `generic/ubuntu1404` with `puppetlabs/ubuntu-14.04-64-nocm` occurrences the box images are being fetched, but then fails on network setup:

```
$ vagrant up
Bringing machine 'ubuntu1404-64-1' up with 'virtualbox' provider...
Bringing machine 'ubuntu1404-64-2' up with 'virtualbox' provider...
==> ubuntu1404-64-1: Box 'puppetlabs/ubuntu-14.04-64-nocm' could not be found. Attempting to find and install...
    ubuntu1404-64-1: Box Provider: virtualbox
    ubuntu1404-64-1: Box Version: >= 0
==> ubuntu1404-64-1: Loading metadata for box 'https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm'
    ubuntu1404-64-1: URL: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
==> ubuntu1404-64-1: Adding box 'puppetlabs/ubuntu-14.04-64-nocm' (v1.0.3) for provider: virtualbox
    ubuntu1404-64-1: Downloading: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm/versions/1.0.3/providers/virtualbox.box
Download redirected to host: s3.amazonaws.com
==> ubuntu1404-64-1: Successfully added box 'puppetlabs/ubuntu-14.04-64-nocm' (v1.0.3) for 'virtualbox'!
==> ubuntu1404-64-1: Importing base box 'puppetlabs/ubuntu-14.04-64-nocm'...
==> ubuntu1404-64-1: Matching MAC address for NAT networking...
==> ubuntu1404-64-1: Checking if box 'puppetlabs/ubuntu-14.04-64-nocm' version '1.0.3' is up to date...
==> ubuntu1404-64-1: Setting the name of the VM: beaker_default_vagrant_hostsyaml_ubuntu1404-64-1_1659338974681_55197
==> ubuntu1404-64-1: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet0", "--ip", "10.255.0.1", "--netmask", "255.255.0.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

Well... It seems the quick_start has a couple of issues as well, however this also demonstrates that vagrant is working outside of beaker.

**Comment by cmhe** [comment]
I also tried it without `rbenv` and use ruby and bundler directly from the Debian 11 repos and it failed similarly.

**Comment by smortex** [comment]
I think it rings a bell: I do have this hack in `~/bin/vagrant` (before anything else in my `$PATH`) so that `vagrant` when run from a Ruby bundle ignore this Ruby bundle completely:

```sh
#!/bin/sh

# Remove all bundler / rbenv environment variables
unset \
  BUNDLE_BIN_PATH \
  BUNDLE_GEMFILE \
  BUNDLE_ORIG_PATH \
  GEM_HOME \
  GEM_PATH \
  RBENV_DIR \
  RBENV_HOOK_PATH \
  RBENV_ROOT \
  RBENV_VERSION \
  RUBYLIB \
  RUBYOPT

# Adjust $PATH to remove rbenv additions
PATH=$(echo ":$PATH:" | sed -re 's,:/tmp/[^:]+/bin:,:,g' -e "s,:${HOME}/bin:,:,g" -e 's,/var/[^/:]+/.rbenv/shims:,,g' -e 's,^:(.*):$,\1,')

echo "===> /usr/local/bin/vagrant $@" >> /tmp/vagrant.log
pwd >> /tmp/vagrant.log
env >> /tmp/vagrant.log

# Run actual vagrant
exec /usr/local/bin/vagrant "$@"
```

I am on FreeBSD and am not sure this is required on systems where Vagrant provide packages, but I recall vaguely using this on Debian too… You may need to adjust a few things, at least the path to "real" vagrant on the last line.  Does it help?

**Comment by cmhe** [comment]
I found out that calling `rake beaker...` directly, without the `bundler exec rake ...`, seems to work.

So I guess that means that rake and the reset of the dependencies need to be installed into the ruby environment and cannot just stay in the project environment via `bundle config set --local path vendor/bundle`.

I also tested with `vagrant-wrapper` but, with that the process just gets stuck.

**Comment by ekohl** [comment]
@smortex does have the right suggestion: you need to either install vagrant inside Bundler, or call vagrant in a way that cleans the environment from bundler.

I have installed vagrant via the Fedora repositories and that has a wrapper that cleans it up.

Having said that, the docs need a serious update. Ubuntu 14.04 is ancient and even if it starts up, I'm not sure how usable it is now.

Taking a step back, I'd recommend [voxpupuli-acceptance](https://github.com/voxpupuli/voxpupuli-acceptance) since it deals with a lot of the complexities involved. I haven't looked into how well it works in a PDK environment, but I wouldn't expect problems.

**Comment by cmhe** [comment]
@ekohl: Well AFAIK installing vagrant inside bundler is no longer supported. At least the latest [gem 1.5.0](https://rubygems.org/gems/vagrant) will complain about it. It also wasn't updated since 2014.

The documentation is somewhat spotty, with stuff [like](https://github.com/voxpupuli/beaker-puppet#how-do-i-use-this): `Then you can call beaker-puppet methods, exactly as you did before.`. Which also doesn't really help if you don't know how it was done before...

I am new to puppet, pdk, rspec, bundler and even ruby, so it could be very well be user error. I am currently just searching for way of least resistance of implementing and maintaining acceptance tests. I noticed that the PDK/puppet officially now supports litmus, but even with that I have [issues](https://github.com/puppetlabs/puppet_litmus/issues/442) and vagrant doesn't seems to work as advertised as well (it seems to just get stuck somewhere)...

Sorry for the rant... Maybe just take it as feedback from a newbie.

**Comment by ekohl** [comment]
The complaints about Beaker documentation are fully justified. It hasn't really been updated in a long time. My goal with voxpupuli-acceptance was to make it easier to consume. Similarly, we have [voxpupuli-test](https://github.com/voxpupuli/voxpupuli-test) for our unit testing. Within Vox Pupuli we don't use PDK but rather things directly.

A quick overview:
* Puppet uses Ruby a lot
* RSpec is a common Ruby testing framework
* For unit testing [rspec-puppet](https://github.com/puppetlabs/rspec-puppet) provides integration with RSpec
* Beaker is a framework to test on machines (virtual, containers)
* [beaker-rspec](https://github.com/voxpupuli/beaker-rspec) provides integration with RSpec
* beaker and beaker-rspec use [serverspec](https://serverspec.org/) to make testing easier

PDK aims to bundle this to make it easier to consume, but IMHO it doesn't. At least when you're an advanced user, it mostly gets in the way. That's why for Vox Pupuli I wrote voxpupuli-test and voxpupuli-acceptance. In https://github.com/voxpupuli/modulesync_config we maintain the templates for our modules.

The biggest difference is that PDK has a lot of boiler plate it templates while in Vox Pupuli I aimed to extract that boiler plate to libraries and have minimal files instead.

**Comment by cmhe** [comment]
@ekohl: Thanks for the reply and for the overview. I will keep the points about PDK in mind. I already found the limits of this template, for instance deactivating honeycomb just [doesn't work](https://github.com/puppetlabs/pdk-templates/issues/477) there.

But I was more successful with litmus for now... well at least the acceptance tests now run on github-actions, but running it locally is currently broken [as well](https://github.com/puppetlabs/puppet_litmus/issues/442) there.

With beaker at least I could install it outside of binder to get the vagrant provisioner to work, but then it failed because `puppet_module_install` wasn't found and it wasn't clear to me how to access the host facts in the testcases. Litmus and the PDK had clearly documented that. Maybe some linking to some example or boilerplate integrations from the documentation would be helpful?

However it seems the vagrant situation seems even worse with litmus compared to beaker, I couldn't find a way to use vagrant with it.

**Comment by ekohl** [comment]
> Maybe some linking to some example or boilerplate integrations from the documentation would be helpful?

Is https://github.com/voxpupuli/voxpupuli-acceptance#usage not sufficient? Would a basic spec test help?

https://github.com/theforeman/puppet-motd/pull/13 is an example using modern spec testing syntax. In most modules you'll find an older style, so that may be a bit confusing.

Of course, that is made easier by already having the boiler plate in place (`Gemfile`, `Rakefile` and `spec_helper_acceptance.rb`), but voxpupuli-acceptance documents those bits.

**Comment by cmhe** [comment]
> > Maybe some linking to some example or boilerplate integrations from the documentation would be helpful?
> 
> Is https://github.com/voxpupuli/voxpupuli-acceptance#usage not sufficient? Would a basic spec test help?

Maybe its about documentation discoverability? When I tried to get beaker running I looked here first:

https://github.com/voxpupuli/beaker/tree/master/docs/tutorials

and especially the quick start:

https://github.com/voxpupuli/beaker/blob/master/docs/tutorials/quick_start_rake_tasks.md

Which I assumed would be a hand holding step by step guide on getting beaker up and running. (It wasn't really...)

Compared to litmus, where I first get linked to a github wiki, which then links to:

https://puppetlabs.github.io/litmus/

That pages is a bit annoying to navigate, because there is no really page index on the side, but it contained a clear guide how to integrate litmus into my own project:

https://puppetlabs.github.io/litmus/Converting-modules-to-use-Litmus.html

And also mentions puppetlabs-motd as an example of a litmus integrated module and how to run tests there:

https://puppetlabs.github.io/litmus/Running-acceptance-tests.html

And finally it described how to write basic tests and how to access puppet facts:

https://puppetlabs.github.io/litmus/Litmus-test-examples.html

with a link to serverspec.

Meanwhile I tried to learn how to read rubydoc documentation to figure out how to access facts in beaker:

https://www.rubydoc.info/gems/beaker-puppet/Beaker/DSL/Helpers/FacterHelpers

> [theforeman/puppet-motd#13](https://github.com/theforeman/puppet-motd/pull/13) is an example using modern spec testing syntax. In most modules you'll find an older style, so that may be a bit confusing.

That looks helpful.

> Of course, that is made easier by already having the boiler plate in place (`Gemfile`, `Rakefile` and `spec_helper_acceptance.rb`), but voxpupuli-acceptance documents those bits.

Yes. It seems like it documents the basic structure. But maybe links to the reference documentation of those functions would be nice. I see that acceptance spec helper in  `puppet-motd` uses `configure_beaker` in more advanced ways...

**Comment by ekohl** [comment]
> Maybe its about documentation discoverability? When I tried to get beaker running I looked here first:

No argument here.

> Yes. It seems like it documents the basic structure. But maybe links to the reference documentation of those functions would be nice. I see that acceptance spec helper in `puppet-motd` uses `configure_beaker` in more advanced ways...

Correct, but I documented that on https://github.com/voxpupuli/voxpupuli-acceptance/#installing-puppet-modules.

**Comment by ekohl** [comment]
I think this is resolved in https://github.com/voxpupuli/beaker-vagrant/pull/73.
